package com.probase.probasepay.enumerations;

public enum BillType {
	DIRECT_TOP_UP, CABLE_TV_SUBSCRIPTION, ELECTRICITY_PURCHASE, PAY_MERCHANT, CREDIT_MERCHANT_MPQR, FUNDS_TRANSFER, VILLAGE_BANKING_GROUP_CONTRIBUTION, VILLAGE_BANKING_LOAN_REPAYMENT
}
