package com.probase.probasepay.enumerations;

public enum GroupLoanStatus {
	ACTIVE, CANCELED, CLOSED, LATE_30, LATE_60, LATE_90, DEFAULTED, APPLYING, REJECTED
	//ACTIVE: CURRENTLY RUNNING
	//CANCELED: CANCELED BY CUSTOMER
	//CLOSED: PAID OFF BY CUSTOMER
	//LATE_30: PAYMENT LATE BEYOND 30 DAYS
	//LATE_60: PAYMENT LATE BEYOND 60 DAYS
	//LATE_90: PAYMENT LATE BEYONG 90 DAYS
	//DEFAULTED: LOAN HAS BEEN CANCELED AND ALL MEASURES TAKEN BUT LOAN REPAYMENTS NOT/NOT FULLY RECOVERED

}
