package com.probase.probasepay.enumerations;

public enum KLVData {
	TRACKING_NUMBER("002"), ORIGINAL_TRANSACTION_AMOUNT("004"), MERCHANT_CATEGORY_CODE("026"), RETRIEVAL_REFERENCE_NUMBER("037"), 
	TERMINAL_ID("041"), MERCHANT_IDENTIFIER("042"), FRAUD_SCORING_DATA("048"), ORIGINAL_CURRENCY_CODE("049"), FROM_ACCOUNT("050"), 
	PIN_BLOCK("052"), MARKUP_AMOUNT("085"), CAPTURE_MODE("250"), NETWORK("251"), FEE_TYPE("252"), LAST_FOUR_DIGITS_PAN("253"), MDES_DIGITIZED_PAN("254"), 
	MDES_DIGITIZED_WALLET_ID("255"), ADJUSTMENT_REASON("256"), REFERENCE_ID("257"), MARKUP_TYPE("258"), SECURE3D_OTP("900"), 
	DIGITIZATION_ACTIVATION("901"), GENERIC_KEY("999");
	
	
	private String value;

	private KLVData(String value) {
	    this.value = value;
	}
	
	public String getValue() {
	    return value;
	}
}
