package com.probase.probasepay.enumerations;

public enum RepaymentStrategy {
	PRINCIPAL_INTEREST_PENALTY, PRINCIPAL_PENALTY_INTEREST, INTEREST_PRINCIPAL_PENALTY, INTEREST_PENALTY_PRINCIPAL, PENALTY_PRINCIPAL_INTEREST, PENALTY_INTEREST_PRINCIPAL
}
