package com.probase.probasepay.enumerations;

public enum ServiceType {

	DEPOSIT_OTC, PAY_MERCHANT, DEBIT_MERCHANT, REVERSE_PAYMENT_TO_MERCHANT,
	DEBIT_CARD, CASHBACK, ADJUSTMENT, CREDIT_CARD, REVERSE_DEBIT_ON_CARD, REVERSE_CREDIT_ON_CARD, 
	CASH_PAYMENT, REVERSE_REFUND, MPQR_WALLET_LOAD, REVERSE_MPQR_WALLET_LOAD, DEBIT_WALLET, CREDIT_WALLET, 
	REVERSE_DEBIT_ON_WALLET, FT_WALLET_TO_WALLET, REVERSE_CREDIT_ON_WALLET, FT_WALLET_TO_CARD, FT_CARD_TO_WALLET, FT_CARD_TO_CARD, 
	AIRTIME_PURCHASE, SERVICE_CHARGE, PAY_MERCHANT_BY_QR, GROUP_CONTRIBUTION, GROUP_CONTRIBUTION_PENALTY, GROUP_LOAN_REPAYMENT
			
}
