package com.probase.probasepay.enumerations;

public enum VillageBankingSetting {
	FUNDS_TRANSFER_INTRA_BANK, FUNDS_TRANSFER_INTER_BANK, FUNDS_TRANSFER_BANK_TO_WALLET, FUNDS_TRANSFER_WALLET_TO_BANK, FUNDS_TRANSFER_WALLET_TO_WALLET, 
	MINIMUM_WALLET_BALANCE, AIRTIME_TOPUP_TRANSACTION_FEE, SCHOOL_FEE_PERCENT, LATE_30_DAYS, LATE_60_DAYS, LATE_90_DAYS, LATE_120_DAYS, LATE_180_DAYS, 
	UTILITY_PAYMENT_TRANSACTION_FEE, CABLETV_PAYMENT_TRANSACTION_FEE, MERCHANT_PAYMENT_TRANSACTION_FEE, RAILWAY_TICKET_TRANSACTION_FEE, INTERNET_DATA_TRANSACTION_FEE, 
	SCHOOL_FEES_TRANSACTION_FEE 
}
