// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateSessionEJBLocator.vsl in andromda-hibernate-cartridge.
//
package com.probase.probasepay.util;

public class ServiceLocator
{
    /**
     * The shared instance of this ServiceLocator.
     */
    private static ServiceLocator instance;

    private ServiceLocator()
    {
        // shouldn't be instantiated
    }

    /**
     * Gets the shared instance of this Class
     *
     * @return the shared service locator instance.
     */
    public static final ServiceLocator getInstance()
    {
        if (instance == null)
        {
            instance = new ServiceLocator();
        }
        return instance;
    }
	/*
    private static Object lookupHome(
        java.util.Hashtable environment,
        String jndiName,
        Class narrowTo) throws javax.naming.NamingException
    {
        javax.naming.InitialContext initialContext = new javax.naming.InitialContext(
            environment);
        try
        {
            Object object = initialContext.lookup(jndiName);
            // only narrow if necessary
            if (narrowTo.isInstance(java.rmi.Remote.class))
            {
                object = javax.rmi.PortableRemoteObject
                    .narrow(object, narrowTo);
            }
            return object;
        }
        finally
        {
            initialContext.close();
        }
    }
	*/
	
    //private static SwpServiceHome swpServiceHome = null;

    /**
     * Gets an instance of <code>smartpay.service.SwpService</code>
     * @throws Exception 
     */
    public final SwpService getSwpService() throws Exception
    {
        try
        {
		/* Commented out by Chimezie Emewulu. We are not using session facade design pattern hence we do not need this part!
            if (swpServiceHome == null)
            {
                swpServiceHome = (smartpay.service.SwpServiceHome)lookupHome(
                    null,
                    smartpay.service.SwpServiceHome.JNDI_NAME,
                    smartpay.service.SwpServiceHome.class);
            }
            return swpServiceHome.create();
		*/
		/*I have modified this to look like this. Let it simply instantiate itself from the smartpay.service.SwpServiceBeanImpl class which of
		course, implements the smartpay.service.SwpService interface. */
			com.probase.probasepay.util.SwpService service = new SwpServiceBeanImpl();
			return service;
        }
        catch (Exception ex)
        {
            throw new Exception(ex);
        }
    }

}